---


AWSTemplateFormatVersion: 2010-09-09


Description: twecs notification module


Metadata:

   AWS::CloudFormation::Interface:
      ParameterLabels:
         Policies:
            default: IAM policies
         PythonVersion:
            default: Python version

      ParameterGroups:
         -
            Label: Lambda
            Parameters:
               - PythonVersion
               - Layers
               - Policies
         -
            Label: twecs
            Parameters:
               - ParameterPath


Parameters:

   IamPath:
      Description: Path under which to create IAM resources.
      Type: String

   Layers:
      Description: ARNs of Lambda layers to add to the function's execution environment.
      Type: CommaDelimitedList

   ParameterPath:
      Description: Parameter Store path whose parameters should be passed to the called function.
      Type: String

   Policies:
      Description: ARNs of IAM managed policies to attach to the function's role.
      Type: CommaDelimitedList

   PythonVersion:
      Description: Python version to use.
      Type: String
      Default: '3.8'


Resources:

   Function:
      Type: AWS::Lambda::Function
      Properties:
         Code:
            ZipFile: |
               from twecs.drivers.aws.lambda_.handlers.notifier import entry_point
         Description: twecs notifier
         Environment:
            Variables:
               NOTIFIER:
                  Ref: Notifier
               PARAMETER_PATH:
                  Ref: ParameterPath
         Handler: index.entry_point
         Layers:
            Ref: Layers
         MemorySize: 128
         Role:
            Fn::GetAtt:
               - FunctionRole
               - Arn
         Runtime:
            Fn::Sub: python${PythonVersion}
         Tags:
            -
               Key: 'twecs:purpose'
               Value: runtime
         Timeout: 15

   FunctionRole:
      Type: AWS::IAM::Role
      Properties:
         Path:
            Ref: IamPath
         AssumeRolePolicyDocument:
            Version: 2012-10-17
            Statement:
               -
                  Principal:
                     Service:
                        - lambda.amazonaws.com
                  Action:
                     - sts:AssumeRole
                  Effect: Allow
         ManagedPolicyArns:
            Ref: Policies
         Policies:
            -
               PolicyName: parameters
               PolicyDocument:
                  Version: 2012-10-17
                  Statement:
                     -
                        Action:
                           - ssm:GetParametersByPath
                        Resource:
                           -
                              Fn::Sub: arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter${ParameterPath}
                        Effect: Allow
         Tags:
            -
               Key: 'twecs:purpose'
               Value: security

   Mapping:
      Type: AWS::Lambda::EventSourceMapping
      Properties:
         EventSourceArn:
            Fn::GetAtt:
               - Queue
               - Arn
         FunctionName:
            Fn::GetAtt:
               - Function
               - Arn
         BatchSize: 1
         Enabled: true
         Tags:
            -
               Key: 'twecs:purpose'
               Value: runtime

   Queue:
      Type: AWS::SQS::Queue
      Properties:
         Tags:
            -
               Key: 'twecs:purpose'
               Value: runtime

   QueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
         Queues:
            -
               Ref: Queue
         PolicyDocument:
            Version: 2012-10-17
            Statement:
                  Principal: '*'
                  Action:
                     - 'sqs:SendMessage'
                  Resource:
                     -
                        Fn::GetAtt:
                           - Queue
                           - Arn
                  Condition:
                     ArnEquals:
                        aws:SourceArn:
                           Ref: NotificationTopicArn
                  Effect: Allow
         # FIXME: tag when supported
         #Tags:
         #   -
         #      Key: 'twecs:purpose'
         #      Value: security

   Subscription:
      Type: AWS::SNS::Subscription
      Properties:
         TopicArn:
            Ref: NotificationTopicArn
         Protocol: sqs
         Endpoint:
            Fn::GetAtt:
               - Queue
               - Arn
         RawMessageDelivery: true
         # FIXME: tag when supported
         #Tags:
         #   -
         #      Key: 'twecs:purpose'
         #      Value: runtime
