---


AWSTemplateFormatVersion: 2010-09-09


Description: Repository for twecs Lambda deployment packages


Resources:

   Bucket:
      Type: AWS::S3::Bucket
      Properties:
         Tags:
            -
               Key: 'twecs:purpose'
               Value: deployment


Outputs:

   BucketName:
      Description: Name of the S3 bucket.
      Value:
         Ref: Bucket
